#!/bin/bash
# Mit diesem Script wird der Docker Hub build Prozess gehooked, 
# damit mehrere Tags auf einmal gebaut werden können.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $DIR/versions.sh

while read -r line; do
    if [ ${#line} -ne 0 ]; then  # Ignore the empty lines
        eval "$line source $DIR/build.sh"
    fi
done <<< "$VARS"