#!/bin/bash
# Mit diesem Script wird der Docker Hub push Prozess gehooked, 
# damit mehrere Tags auf einmal in das Repository gepushed werden können.


# Nur pushen wenn der Commit auf dem master ist
echo "Aktueller Branch: $SOURCE_BRANCH"
if [ "${SOURCE_BRANCH}" != "master" ]; then
    exit 0
fi

for tag in $(docker images robertschreib/docker-compose-openjdk-node-gradle-test --format "{{.Tag}}");
do
    echo "TAG: '${tag}'"
    if [[ $tag != "<none>" ]]; then
        echo "Tag: '${tag}' wird gepushed!"
        docker push "robertschreib/docker-compose-openjdk-node-gradle-test:${tag}"
    fi
done
