#!/bin/bash

set -e

# Don't push images if branch is not master
echo "Current Branch: $SOURCE_BRANCH"
if [ "${SOURCE_BRANCH}" != "master" ]; then
    exit 0
fi

for tag in $(docker images emundo/docker-compose-openjdk-node-gradle --format "{{.Tag}}");
do
    docker push "${DOCKER_REPO}:${tag}"
done
