#!/bin/bash
# Mit diesem Script wird der Docker Hub build Prozess gehooked, 
# damit mehrere Tags auf einmal gepushed werden können.


# Nur pushen wenn der Commit auf dem master ist
echo "Current Branch: $SOURCE_BRANCH"
if [ "${SOURCE_BRANCH}" != "master" ]; then
    exit 0
fi

for tag in $(docker images emundo/docker-compose-openjdk-node-gradle --format "{{.Tag}}");
do
    docker push "emundo/docker-compose-openjdk-node-gradle:${tag}"
done
