#!/bin/bash
export IMAGE='emundo/docker-compose-openjdk-node-gradle'
export VARS='
JDK_VERSION=14 GRADLE_VERSION=6 IMAGE_TAG="openjdk-14-gradle-6" EXTRA_TAGS="openjdk-14"
JDK_VERSION=13 GRADLE_VERSION=6 IMAGE_TAG="openjdk-13-gradle-6 EXTRA_TAGS="openjdk-13"
JDK_VERSION=12 GRADLE_VERSION=5.4 IMAGE_TAG="openjdk-12-gradle-5.4"
JDK_VERSION=12 GRADLE_VERSION=5.5 IMAGE_TAG="openjdk-12-gradle-5.5"
JDK_VERSION=12 GRADLE_VERSION=5.6 IMAGE_TAG="openjdk-12-gradle-5.6"
JDK_VERSION=12 GRADLE_VERSION=5 IMAGE_TAG="openjdk-12-gradle-5" EXTRA_TAGS="openjdk-12"
JDK_VERSION=12 GRADLE_VERSION=6 IMAGE_TAG="openjdk-12-gradle-6"
JDK_VERSION=11 GRADLE_VERSION=5.4 IMAGE_TAG="openjdk-11-gradle-5.4"
JDK_VERSION=11 GRADLE_VERSION=5.5 IMAGE_TAG="openjdk-11-gradle-5.5"
JDK_VERSION=11 GRADLE_VERSION=5.6 IMAGE_TAG="openjdk-11-gradle-5.6"
JDK_VERSION=11 GRADLE_VERSION=5 IMAGE_TAG="openjdk-11-gradle-5" EXTRA_TAGS="openjdk-11"
JDK_VERSION=11 GRADLE_VERSION=6 IMAGE_TAG="openjdk-11-gradle-6"
JDK_VERSION=11 GRADLE_VERSION=4.10 IMAGE_TAG="openjdk-11-gradle-4.10"
JDK_VERSION=8 GRADLE_VERSION=5.4 IMAGE_TAG="openjdk-8-gradle-5.4"
JDK_VERSION=8 GRADLE_VERSION=5.5 IMAGE_TAG="openjdk-8-gradle-5.5"
JDK_VERSION=8 GRADLE_VERSION=5.6 IMAGE_TAG="openjdk-8-gradle-5.6"
JDK_VERSION=8 GRADLE_VERSION=5 IMAGE_TAG="openjdk-8-gradle-5"
JDK_VERSION=8 GRADLE_VERSION=6 IMAGE_TAG="openjdk-8-gradle-6"
JDK_VERSION=8 GRADLE_VERSION=4.10 IMAGE_TAG="openjdk-8-gradle-4.10" EXTRA_TAGS="openjdk-8;latest"
'
